# Generated by Django 5.2.4 on 2025-07-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('imagem', models.ImageField(upload_to='categoria_imagens/')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('imagens', models.ImageField(upload_to='imagens/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_doces.categoria')),
            ],
        ),
    ]
