# Generated by Django 5.2.4 on 2025-07-22 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_doces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagens',
        ),
        migrations.CreateModel(
            name='ImagemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_doces.produto')),
            ],
        ),
    ]
