# Generated by Django 5.2.4 on 2025-07-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_doces', '0002_remove_produto_imagens_imagemproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
