# Generated by Django 5.2.4 on 2025-07-25 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_doces', '0004_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemproduct',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='gestao_doces.produto'),
        ),
    ]
