# Generated by Django 5.2.4 on 2025-07-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_doces', '0006_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='carrinho',
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
        migrations.DeleteModel(
            name='ItemCarrinho',
        ),
    ]
