# Generated by Django 5.2.4 on 2025-08-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_doces', '0009_rename_image_imageproduct_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageproduct',
            old_name='produto',
            new_name='product',
        ),
    ]
