# Generated by Django 5.2.4 on 2025-07-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao_doces', '0004_alter_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('favoritos', models.ManyToManyField(blank=True, related_name='clientes_que_favoritaram', to='gestao_doces.produto')),
            ],
        ),
    ]
