# Generated by Django 5.2.4 on 2025-07-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_bairro_cliente_numero_cliente_rua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='nao', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default='nao', max_length=128),
            preserve_default=False,
        ),
    ]
