# Generated by Django 5.2.4 on 2025-07-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_endereco_cliente_email_cliente_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='senha',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
