# Generated by Django 5.2.4 on 2025-08-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rua',
        ),
    ]
